datasource:
  driverClassName: com.mysql.cj.jdbc.Driver
  username: cloud
  password: MzpMkssGLa2RjZXf
  url: jdbc:mysql://localhost:3306/cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
