name: NFCAT_PLUGIN
main: com.nfcat.papermc.Main
version: 1.0.2
author: nfcat.com
description: 一个自己用的小插件
website: https://nfcat.com

commands:
  menu:
    description: 命令执行 输入/menu 获取帮助
    usage: /m 参数(?)
    aliases:
      - m

#permissions:
#  man.*:
#    description: Gives access to all doorman commands #给予使用man所有命令的权限
#    children:  #子权限节点
#      man.kick: true
#      man.ban: true
#      man.knock: true
#      man.denied: false
#  man.kick:
#    description: Allows you to kick a user  #允许你踢出一名用户
#    default: op  #OP默认拥有该权限
#  man.ban:
#    description: Allows you to ban a user  #允许你封禁一名用户
#    default: op #OP默认拥有该权限
#  man.knock:
#    description: Knocks on the door! #敲门
#    default: true #全员默认拥有该权限
#  man.denied:
#    description: Prevents this user from entering the door  #禁止拥有该权限节点的用户进入门内


#permissions:
#  test*:
#    description: Gives access to all doorman commands  //翻译见上
#    children:
#      test.kick: true
#      test.ban: true
#      test.knock: true
#      test.denied: false
