/*
 * This file is generated by MybatisHelperPro plug-in. For details, please see：
 *
 * https://gitee.com/lsl-gitee/LDevKit/tree/master/MybatisHelperPro
 * or
 * https://plugins.jetbrains.com/plugin/15913-mybatishelperpro
 */
package com.nfcat.papermc.sql.mapper;

import com.nfcat.papermc.sql.entry.NfMcCard;

/**
 * @author MybatisHelperPro
 * @since 2022/09/27 15:58
 */
public interface NfMcCardMapper {

    int insert(NfMcCard record);

    int insertSelective(NfMcCard record);

    int update(NfMcCard record);

    int updateSelective(NfMcCard record);

    NfMcCard queryOne(String card);

    int delete(String card);
}