/*
 * This file is generated by MybatisHelperPro plug-in. For details, please see：
 *
 * https://gitee.com/lsl-gitee/LDevKit/tree/master/MybatisHelperPro
 * or
 * https://plugins.jetbrains.com/plugin/15913-mybatishelperpro
 */
package com.nfcat.papermc.sql.mapper;

import com.nfcat.papermc.sql.entry.NfMcUser;
import org.apache.ibatis.annotations.Param;

/**
 * @author MybatisHelperPro
 * @since 2022/09/27 10:55
 */
public interface NfMcUserMapper {

    int insert(NfMcUser record);

    int insertSelective(NfMcUser record);

    int update(NfMcUser record);

    int updateSelective(NfMcUser record);

    NfMcUser queryOne(String mcName);

    int delete(String mcName);

    boolean login(@Param("mcName") String mcName, @Param("password") String password);

    int changepass(@Param("mcName") String mcName, @Param("oldPassword") String oldPassword, @Param("password") String password);

    int addGold(@Param("mcName") String mcName, @Param("addGold") Long addGold);

}