/*
 * This file is generated by MybatisHelperPro plug-in. For details, please see：
 *
 * https://gitee.com/lsl-gitee/LDevKit/tree/master/MybatisHelperPro
 * or
 * https://plugins.jetbrains.com/plugin/15913-mybatishelperpro
 */
package com.nfcat.papermc.sql.entry;

import lombok.Data;
import lombok.experimental.Accessors;
import java.io.Serializable;
import java.sql.Timestamp;

/**
 * @author MybatisHelperPro
 * @since 2022/09/27 15:58
 */
@Data
@Accessors(chain = true)
public class NfMcCard implements Serializable {
    private static final long serialVersionUID = 1L;
    /**     * 卡密     */    private String card;
    /**     * 1->金币;2->水晶;3->VIP;4->SVIP     */    private Integer type;
    /**     * 创建时间     */    private Timestamp createTime;
    /**     * 使用时间     */    private Timestamp useTime;
    /**     * 使用者名称     */    private String useMcName;
    /**     * 其他信息     */    private String info;
}