name: NFCAT_PLUGIN
main: com.nfcat.spigotmc.Main
version: 1.0.2
author: nfcat.com

commands:
  helpme:
    description: 帮助命令 --- 主菜单->mfcat(m|menu)|登录->login(l)|注册->register(r)|修改密码->changepass(c)
    usage: /helpme 命令
  login:
    description: 登录命令
    usage: /l 密码
    aliases:
      - l
      - log
  register:
    description: 注册命令
    usage: /r 密码 重复密码
    aliases:
      - r
      - reg
  changepass:
    description: 修改密码命令
    usage: /c 原密码 新密码 重复新密码
    aliases:
      - c
  nfcat:
    description: 命令执行 输入helpme获取帮助
    usage: /n 命令 参数
    aliases:
      - n
      - menu

permissions:
  MessageBox.allPlayer:
    description: MessageBox all player permissions.
    default: true